### ISSUE TITLE
Plugin UI too small on a 4k screen

### ISSUE THREAD

**Issue by amadeusp** [Wasted-Audio/wstd-flangr#1]
# Issue(s)
* The plugin is very small on my 4k screen with a resolution of 3840 x 2400
* The scrollbars overlap the plugin UI

# Expected behavior
* The plugin would be displayed in a 200% scale or (ideally) would allow its UI to be scaled
* The scrollbars would be hidden

# Basic system information
* Operating system: Manjaro Linux x86_64
* Kernel: Manjaro Linux x86_64
* Host: ThinkPad Z16 Gen 1
* Desktop environment: GNOME 43.4
* Display protocol: Wayland
* Audio server: PipeWire
* Session and policy manager: WirePlumber
* Digital audio workstation: Bitwig Studio (Flatpak)

# Screen grabs
![WSTD_FLANGR-Screenshot from 2023-04-28 05-26-14](https://user-images.githubusercontent.com/2808562/235007132-c77be69a-8898-47b8-a654-b03443b8fd24.png)
![WSTD_FLANGR-Screenshot from 2023-04-28 05-26-22](https://user-images.githubusercontent.com/2808562/235007148-07b429c8-8752-43fa-8353-3ba6e248e6a4.png)

**Comment by dromer** [comment]
Same issue as https://github.com/Wasted-Audio/wstd-eq/issues/1

**Comment by amadeusp** [comment]
@dromer Will you update this plugin as well? Thanks in advance!

**Comment by dromer** [comment]
All plugins have been updated. Please test.

**Comment by amadeusp** [comment]
@dromer Oddly enough I still can't access the new build on itch.io. There it is listed as a 64 days old build and when downloaded it is the 0.2.2 version.

**Comment by dromer** [comment]
0.2.2 is the latest. The timestamp doesn't change because I simply modify the download links on the same publication so it's a bit misleading :)

**Comment by amadeusp** [comment]
@dromer Ah, I see. :nerd_face: I installed this build now and am happy to report that this is now fixed too! :raised_hands:

**Comment by dromer** [comment]
@amadeusp thnx!
