### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by AnClark** [Wasted-Audio/wstd-flangr#2]
Hi Wasted-Audio!

I want to compile WSTD plugins on my machine. But it seems that neither compile instructions nor build system files (CMakeLists.txt, Makefile, etc.) are provided.

What's more, this software required to be purchased, while source is GPLv3 licensed. It's OK to purchase FOSS software, which helps developers, but in my opinion, allowing users to build by their own matters as well.

Thanks.

**Comment by dromer** [comment]
At the moment you can read the instructions from the build yaml file: https://github.com/Wasted-Audio/wstd-flangr/blob/master/.github/workflows/build.yml
